### ISSUE TITLE
小哥哥你好，很喜欢您的字体风格，

### ISSUE THREAD

**Issue by Palpitation-github** [geekplux/ama#7]
小哥哥你好，很喜欢您的字体风格，但是我用的是另外的主题，我希望能得到您的文字效果请问是直接修改body的font-family样式为楷体，并且修改粗细就可以嘛，还是需要内置一些库什么的。不太了解希望可以指点一下，打扰您了，，蟹蟹

**Comment by geekplux** [comment]
```css
body {
  font-family: Baskerville, "Times New Roman", "Liberation Serif", STFangsong, FangSong, FangSong_GB2312, "CWTEX\-F", serif;
  font-size: 20px;
}


h1, h2, h3, h4, h5, h6 {
  font-family: Baskerville, Georgia, "Liberation Serif", "Kaiti SC", STKaiti, "AR PL UKai CN", "AR PL UKai HK", "AR PL UKai TW", "AR PL UKai TW MBE", "AR PL KaitiM GB", KaiTi, KaiTi_GB2312, DFKai-SB, "TW\-Kai", serif;
}
```

https://github.com/geekplux/hexo-theme-typing/blob/master/source/css/source.css#L54-L61
